import type { Metadata } from "next";
import localFont from "next/font/local";
import { Geist, Geist_Mono } from "next/font/google";
import GlobalScrollBlur from "@/components/GradualBlur/GlobalScrollBlur";
import SiteFooter from "@/components/SiteFooter";
import SiteHeader from "@/components/SiteHeader";
import "./globals.css";

const passionOne = localFont({
  src: [
    { path: "../../fonts/PassionOne-Regular.ttf", weight: "400", style: "normal" },
    { path: "../../fonts/PassionOne-Bold.ttf", weight: "700", style: "normal" },
    { path: "../../fonts/PassionOne-Black.ttf", weight: "900", style: "normal" },
  ],
  variable: "--font-passion-one",
  display: "swap",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${passionOne.variable} ${geistSans.variable} ${geistMono.variable} h-full snap-y snap-proximity scroll-smooth antialiased`}
    >
      <body className="relative z-[1] min-h-full text-center">
        <div className="relative flex min-h-full flex-col pb-[calc(14rem+env(safe-area-inset-bottom,0px))] sm:pb-[calc(16rem+env(safe-area-inset-bottom,0px))]">
          <SiteHeader />
          {children}
          <SiteFooter />
          <GlobalScrollBlur />
        </div>
      </body>
    </html>
  );
}
