export const previewEvents = [
  {
    home: "Watch party",
    away: "All welcome",
    location: "City centre",
    date: "Sat 14 Jun · 15:00",
    emoji: "👥",
  },
  {
    home: "MEET UP",
    away: "Mixed teams",
    location: "Local pitch",
    date: "Sun 15 Jun · 12:30",
    emoji: "🤝",
  },
  {
    home: "Final screening",
    away: "Open invite",
    location: "Sports bar",
    date: "Wed 18 Jun · 19:45",
    emoji: "🍻",
  },
  {
    home: "Meet-up",
    away: "Anyone?",
    location: "Near you",
    date: "Fri 20 Jun · 19:00",
    emoji: "📍",
  },
  {
    home: "Watch party",
    away: "All welcome",
    location: "Riverside venue",
    date: "Sat 21 Jun · 17:30",
    emoji: "🏟️",
  },
  {
    home: "MEET UP",
    away: "Mixed teams",
    location: "Indoor hall",
    date: "Sun 22 Jun · 14:00",
    emoji: "💬",
  },
  {
    home: "Final screening",
    away: "Open invite",
    location: "Fan zone",
    date: "Mon 23 Jun · 20:00",
    emoji: "📣",
  },
  {
    home: "Meet-up",
    away: "Anyone?",
    location: "Town centre",
    date: "Tue 24 Jun · 19:45",
    emoji: "🚌",
  },
  {
    home: "Watch party",
    away: "All welcome",
    location: "Community space",
    date: "Thu 26 Jun · 18:00",
    emoji: "🦁",
  },
  {
    home: "MEET UP",
    away: "Mixed teams",
    location: "Park pitch",
    date: "Fri 27 Jun · 19:30",
    emoji: "🎉",
  },
] as const;

export type PreviewEvent = (typeof previewEvents)[number];

/** Local photos for hologram pop-out cards (aligned by index with `previewEvents`). Cycles 6 assets across 10 pins. */
const PREVIEW_EVENT_IMAGES = [
  "/preview-event-img-7720.jpg",
  "/preview-event-5431.png",
  "/preview-event-0375.png",
  "/preview-event-9179.png",
  "/preview-event-5788.png",
  "/preview-event-5270.png",
] as const;

const GENERIC_HEADLINES = [
  "WORLD CUP WATCH PARTIES",
  "MEET UP",
  "WOMEN'S CHAMPIONS LEAGUE FINAL",
  "MEET UP ANYONE?",
] as const;

export const previewEventCardPresentation = [
  {
    headline: GENERIC_HEADLINES[0],
    friendLead: "Charlotte",
    extraFriends: 3,
    going: 5,
    miles: 66,
    shortDate: "14/06/26",
    crowdSrc: PREVIEW_EVENT_IMAGES[0],
  },
  {
    headline: GENERIC_HEADLINES[1],
    friendLead: "Maya",
    extraFriends: 2,
    going: 8,
    miles: 42,
    shortDate: "15/06/26",
    crowdSrc: PREVIEW_EVENT_IMAGES[1],
  },
  {
    headline: GENERIC_HEADLINES[2],
    friendLead: "Alex",
    extraFriends: 5,
    going: 12,
    miles: 18,
    shortDate: "18/06/26",
    crowdSrc: PREVIEW_EVENT_IMAGES[2],
  },
  {
    headline: GENERIC_HEADLINES[3],
    friendLead: "Jordan",
    extraFriends: 4,
    going: 7,
    miles: 53,
    shortDate: "20/06/26",
    crowdSrc: PREVIEW_EVENT_IMAGES[3],
  },
  {
    headline: GENERIC_HEADLINES[0],
    friendLead: "Sam",
    extraFriends: 2,
    going: 9,
    miles: 31,
    shortDate: "21/06/26",
    crowdSrc: PREVIEW_EVENT_IMAGES[4],
  },
  {
    headline: GENERIC_HEADLINES[1],
    friendLead: "Riley",
    extraFriends: 3,
    going: 6,
    miles: 24,
    shortDate: "22/06/26",
    crowdSrc: PREVIEW_EVENT_IMAGES[5],
  },
  {
    headline: GENERIC_HEADLINES[2],
    friendLead: "Taylor",
    extraFriends: 6,
    going: 15,
    miles: 71,
    shortDate: "23/06/26",
    crowdSrc: PREVIEW_EVENT_IMAGES[0],
  },
  {
    headline: GENERIC_HEADLINES[3],
    friendLead: "Casey",
    extraFriends: 1,
    going: 4,
    miles: 12,
    shortDate: "24/06/26",
    crowdSrc: PREVIEW_EVENT_IMAGES[1],
  },
  {
    headline: GENERIC_HEADLINES[0],
    friendLead: "Morgan",
    extraFriends: 4,
    going: 10,
    miles: 88,
    shortDate: "26/06/26",
    crowdSrc: PREVIEW_EVENT_IMAGES[2],
  },
  {
    headline: GENERIC_HEADLINES[1],
    friendLead: "Charlie",
    extraFriends: 3,
    going: 11,
    miles: 29,
    shortDate: "27/06/26",
    crowdSrc: PREVIEW_EVENT_IMAGES[3],
  },
] as const;

/** Emoji bubble positions (% of projection area) + staggered motion delay */
export const hologramBubbleLayout = [
  { eventIndex: 0 as const, x: 9, y: 14, motionDelay: "0s" },
  { eventIndex: 1 as const, x: 26, y: 26, motionDelay: "0.14s" },
  { eventIndex: 2 as const, x: 46, y: 11, motionDelay: "0.28s" },
  { eventIndex: 3 as const, x: 62, y: 22, motionDelay: "0.42s" },
  { eventIndex: 4 as const, x: 78, y: 13, motionDelay: "0.56s" },
  { eventIndex: 5 as const, x: 90, y: 27, motionDelay: "0.7s" },
  { eventIndex: 6 as const, x: 17, y: 42, motionDelay: "0.84s" },
  { eventIndex: 7 as const, x: 40, y: 48, motionDelay: "0.98s" },
  { eventIndex: 8 as const, x: 54, y: 38, motionDelay: "1.12s" },
  { eventIndex: 9 as const, x: 72, y: 44, motionDelay: "1.26s" },
] as const;
